### ISSUE TITLE
Package to support Typescript; support Angular and other frameworks

### ISSUE THREAD

**Issue by klihelp** [dixonandmoe/tessarray#17]
Package to support Typescript; support Angular and other frameworks

**Comment by markjanzer** [comment]
Hey klihelp, 

I'm almost done with a revision and improvement of Tessarray and its implementation that allows for more flexibility, some IE compatibility, and plenty of other things. I've been almost done with it for a few months now, but I temporarily stopped working on it. I'm starting to work on it again, and I'm going to try to complete the revision soon, and when I do I'll package it up. I don't want to package beforehand because this push will contain potentially breaking changes.
